name: NWPlay

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm i
      - run: npm run dist
      - run: node tools/createWindowsSetup
      - uses: actions/upload-artifact@v2
        with:
          name: macos-x64
          path: dist/apps/dist/*mac*.zip
      - uses: actions/upload-artifact@v2
        with:
          name: linux-x86
          path: dist/apps/dist/*linux-x86*.zip
      - uses: actions/upload-artifact@v2
        with:
          name: linux-x64
          path: dist/apps/dist/*linux-x64*.zip
      - uses: actions/upload-artifact@v2
        with:
          name: windows-x86
          path: dist/apps/dist/*win-x86*.zip
      - uses: actions/upload-artifact@v2
        with:
          name: windows-x64
          path: dist/apps/dist/**/*win-x64*.zip
      - uses: actions/upload-artifact@v2
        with:
          name: windows-x64-install
          path: dist/apps/dist/**/*win-x64*.exe
      - uses: actions/upload-artifact@v2
        with:
          name: windows-x86-install
          path: dist/apps/dist/*win-x86*.exe
